version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-php-app
    container_name: lms-php-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_URL=${DB_URL}
    depends_on: []

  nginx:
    image: nginx:1.25
    container_name: lms-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# No database container included, as you will connect directly to Supabase
# Make sure your .env file has the correct Supabase credentials
